# Generated by Django 5.1.7 on 2025-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prac_Form', '0004_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
