# Generated by Django 5.1.6 on 2025-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_list_assigned_by_alter_todo_list_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], max_length=6),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=9),
        ),
    ]
