# Generated by Django 5.1.6 on 2025-03-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_todolist_assigned_to_alter_todolist_assigned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Mentee'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
